print("Please enter your name.")
name = input()
print("What do you like to do?")
hobby = input()
print("How old are you?")
age = input()
print("What is your favorite food?")
food = input()
print(name,'likes',hobby,'and is',age)
print(name,'loves',food)